Repository print4health/print4health, pull requests merged in 2020-04, with the labels that each got.

#214 feature/hubs
  assets/js/component/map/index-map.js
  assets/js/component/map/marker-maker.js
  assets/js/component/map/marker-requester-hub.js
  assets/js/component/map/marker-requester.js
  fixtures/Maker.yml
  fixtures/Order.yml
  fixtures/Requester.yml
  src/Domain/User/Entity/Requester.php
  src/Infrastructure/Controller/MakerController.php
  src/Infrastructure/Dto/Maker/MakerGeoDataResponse.php
  src/Infrastructure/Dto/Requester/RequesterResponse.php
  src/Infrastructure/Migrations/Version20200329111848.php
  tests/Controller/MakerControllerTest.php
Labels: backend, frontend

#216 contact form
  assets/js/app.js
  assets/js/component/footer/footer.js
  assets/js/container/contact/contact.js
  assets/scss/app.scss
  assets/scss/partials/_utils.scss
  config/services.yaml
  src/Domain/Contact/Mailer.php
  src/Infrastructure/Controller/ContactController.php
  src/Infrastructure/Dto/Contact/ContactRequest.php
  templates/email/contact_form.html.twig
Labels: backend, frontend

#272 feature/cypress-ci
  .eslintrc.json
  .github/workflows/main.yml
  README.md
  assets/js/config.js
  config/services.yaml
  cypress.json
  cypress/integration/anonymous_spec.js
  cypress/integration/contact_form_spec.js
  cypress/integration/maker_registration_spec.js
  cypress/integration/maker_spec.js
  cypress/integration/requester_spec.js
  cypress/integration/things_search_spec.js
  cypress/integration/user_spec.js
  cypress/support/commands.js
Labels: CI, backend, frontend

#267 feature/dashbord-contact
  assets/img/id-card-solid.svg
  assets/js/app.js
  assets/js/component/security/PrivateRoute.js
  assets/js/container/dashboard/contact.js
  assets/js/container/dashboard/dashboard.js
  assets/scss/partials/_components.scss
  src/Domain/User/Entity/Maker.php
  src/Domain/User/Entity/Requester.php
  src/Domain/User/Entity/User.php
  src/Infrastructure/Controller/MakerController.php
  src/Infrastructure/Controller/OrderController.php
  src/Infrastructure/Controller/RequesterController.php
  src/Infrastructure/Dto/Order/OrderResponse.php
Labels: frontend

#282 changed text for modals with link to new registration forms
  assets/js/component/modal/commit.js
  assets/js/component/modal/order.js
Labels: frontend

#281 deployment/develop-to-master
  .php_cs.dist
  assets/js/app.js
  assets/js/component/modal/commit.js
  assets/js/component/modal/order.js
  assets/js/component/user/user-nav.js
  assets/js/container/dashboard/contact.js
  assets/js/container/dashboard/dashboard.js
  assets/scss/partials/_components.scss
  cypress/support/commands.js
  src/Domain/Commitment/Entity/Commitment.php
  src/Domain/Order/Entity/Order.php
  src/Domain/User/Entity/User.php
  src/Domain/User/UserInterface.php
  src/Infrastructure/Command/UpdateUserLatLngCommand.php
  src/Infrastructure/Controller/MakerRegistrationController.php
  src/Infrastructure/Controller/OrderController.php
  src/Infrastructure/Dto/Commitment/CommitmentResponse.php
  src/Infrastructure/Dto/Maker/MakerResponse.php
  src/Infrastructure/Dto/Order/OrderResponse.php
  src/Infrastructure/Dto/User/OrderContactUserDetailResponse.php
  src/Infrastructure/Migrations/Version20200412125650.php
  src/Infrastructure/Services/GeoCoder.php
  src/Infrastructure/Validator/ThingExistsValidator.php
  tests/Service/GeoCoderServiceTest.php
Labels: deployment

#295 bug/18n-empty-onload
  assets/js/i18n.js
  public/locales/de/translation.json
  public/locales/en/translation.json
Labels: frontend, i18n
