Repository print4health/print4health, pull requests merged in 2020-03, with the labels that each got.

#36 task/actions-ci
  .github/workflows/main.yml
Labels: enhancement

#70 #54
  config/packages/security.yaml
  fixtures/Order.yml
  fixtures/Requester.yml
  fixtures/User.yml
  print4health.postman_collection.json
  src/Alice/Processor/PasswordProcessor.php
  src/Controller/OrderController.php
  src/Controller/RequesterController.php
  src/Controller/SecurityController.php
  src/Controller/UserController.php
  src/Dto/OrderOut.php
  src/Dto/RequesterIn.php
  src/Dto/RequesterOut.php
  src/Dto/User.php
  src/Entity/Order.php
  src/Entity/User/Requester.php
  src/Entity/User/User.php
  src/Entity/User/UserInterface.php
  src/Migrations/Version20200322163538.php
  src/Repository/RequesterRepository.php
  src/Repository/UserRepository.php
Labels: backend

#57 api-doc
  README.md
  composer.json
  composer.lock
  config/bundles.php
  config/packages/nelmio_api_doc.yaml
  config/routes/nelmio_api_doc.yaml
  src/Controller/OrderController.php
  src/Controller/SecurityController.php
  src/Controller/UserController.php
  src/Dto/OrderIn.php
  src/Dto/OrderOut.php
  src/Dto/ThingOut.php
  src/Dto/User.php
  symfony.lock
Labels: documentation

#52 Frontend styling
  assets/js/app.js
  assets/js/component/search/search.js
  assets/js/component/user/user-nav.js
  assets/js/container/faq/faq.js
  assets/js/container/index/index.js
  assets/js/container/thing-list/thing-list.js
  assets/scss/app.scss
  assets/scss/partials/_variables.scss
  package-lock.json
Labels: frontend

#73 adding faq to navbar
  assets/js/app.js
Labels: frontend

#74 Fix/menu
  assets/js/component/user/user-nav.js
  assets/scss/app.scss
Labels: frontend

#43 post commitment
  .github/workflows/main.yml
  print4health.postman_collection.json
  src/Controller/CommitmentController.php
  src/Dto/Commitment.php
  src/Dto/CommitmentIn.php
  src/Dto/CommitmentOut.php
Labels: backend

#78 Content for Startpage
  assets/js/container/index/index.js
Labels: frontend

#81 Content for FAQ page
  assets/js/container/faq/faq.js
Labels: frontend

#83 Content/startpage
  assets/js/container/index/index.js
Labels: frontend

#80 Feature/add tests
  .env.test
  .gitignore
  bin/phpunit
  composer.json
  composer.lock
  config/bundles.php
  config/packages/test/dama_doctrine_test_bundle.yaml
  phpunit.xml.dist
  src/Controller/SecurityController.php
  symfony.lock
  tests/Controller/AbstractControllerTest.php
  tests/Controller/RequesterControllerTest.php
  tests/bootstrap.php
Labels: backend

#84 WIP: Content/all sites
  assets/js/container/faq/faq.js
  assets/js/container/index/index.js
Labels: frontend

#85 Feature/user context
  assets/js/app.js
  assets/js/component/modal/login.js
  assets/js/component/user/user-nav.js
  assets/js/context/app-context.js
Labels: frontend

#91 feature/thing-list-styling
  .nvmrc
  assets/js/component/search/search.js
  assets/js/component/thing/list-item.js
  assets/js/component/thing/list.js
  assets/scss/app.scss
  assets/scss/partials/_component-thing-list.scss
  assets/scss/partials/_components.scss
Labels: frontend

#92 composer version fixed
  composer.json
Labels: backend

#89 Feature/logo clickable
  assets/js/app.js
Labels: frontend

#95 Commitment api endpoint
  Makefile
  src/Controller/CommitmentController.php
Labels: backend

#122 Wording fixes
  assets/js/container/faq/faq.js
  assets/js/container/imprint/imprint.js
  assets/js/container/index/index.js
  assets/js/container/thing/list.js
  assets/scss/partials/_variables.scss
Labels: frontend

#147 add meta info about project to readme
  README.md
Labels: documentation

#151 Feature/map
  assets/js/component/map/marker-order.js
  assets/js/component/map/requirement-map.js
  assets/js/container/thing/detail.js
  assets/scss/app.scss
  assets/scss/partials/_map.scss
  fixtures/Order.yml
  fixtures/Requester.yml
  package.json
  yarn.lock
Labels: frontend

#170 deployment/develop-to-master
  .php_cs.dist
  composer.json
  composer.lock
  config/bundles.php
  config/packages/dev/monolog.yaml
  config/packages/prod/monolog.yaml
  config/packages/test/monolog.yaml
  symfony.lock
Labels: deployment

#182 Fix/existing order
  src/Domain/Order/Entity/Order.php
  src/Infrastructure/Controller/OrderController.php
Labels: backend

#186 modal handling
  .editorconfig
  assets/js/app.js
  assets/js/component/modal/login.js
  assets/js/component/user/user-nav.js
Labels: frontend

#187 responsive navbar
  assets/js/app.js
Labels: frontend

#181 Feature/commit to order
  .eslintrc.json
  assets/js/app.js
  assets/js/component/map/marker-order.js
  assets/js/component/map/requirement-map.js
  assets/js/component/modal/commit.js
  assets/js/component/modal/order.js
  assets/js/container/thing/detail.js
  assets/scss/partials/_container.scss
  assets/scss/partials/_map.scss
  fixtures/Commitment.yml
  fixtures/Order.yml
  fixtures/Requester.yml
  package.json
  src/Domain/Commitment/Entity/Commitment.php
  src/Domain/User/Entity/Requester.php
  src/Infrastructure/Controller/CommitmentController.php
  src/Infrastructure/Dto/Order/OrderResponse.php
  src/Infrastructure/Migrations/Version20200326113917.php
  webpack.config.js
  yarn.lock
Labels: backend, frontend

#194 Feature/cleanup modals
  assets/js/app.js
  assets/js/component/user/user-nav.js
Labels: frontend

#198 fix user logged in state
  assets/js/component/modal/login.js
  assets/js/component/user/user-nav.js
Labels: bug, frontend

#206 feature: meta tags / social
  public/print4health.jpg
  templates/base.html.twig
Labels: enhancement

#205 Fix/switch eslint
  .github/workflows/main.yml
Labels: CI, bug

#207 feature/dashbord
  assets/js/app.js
  assets/js/component/security/PrivateRoute.js
  assets/js/component/user/user-nav.js
  assets/js/container/dashboard/dashboard.js
  assets/scss/partials/_components.scss
  src/Domain/Exception/NotFoundException.php
  src/Domain/Order/NotFoundException.php
  src/Domain/User/NotFoundException.php
  src/Domain/User/RequesterNotFoundException.php
  src/Infrastructure/Controller/OrderController.php
Labels: backend, frontend

#197 Feature/frontend tests
  .gitignore
  ansible/roles/app/meta/main.yml
  ansible/roles/cypress-deps/tasks/main.yml
  assets/js/component/modal/commit.js
  assets/js/component/modal/order.js
  cypress.json
  cypress/integration/anonymous_spec.js
  cypress/integration/maker_spec.js
  cypress/integration/requester_spec.js
  cypress/integration/user_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package.json
  yarn.lock
Labels: frontend, infrastructure

#218 fix/dashbord-reload
  assets/js/app.js
  assets/js/container/dashboard/dashboard.js
  cypress/integration/anonymous_spec.js
  cypress/integration/maker_spec.js
  cypress/integration/requester_spec.js
  cypress/integration/user_spec.js
  yarn.lock
Labels: bug

#202 #141 maker registration
  ansible/roles/tools/tasks/main.yml
  assets/2000px-Karte_Deutschland.svg
  assets/js/app.js
  assets/js/component/user/user-nav.js
  assets/js/container/data-privacy-statement/data-privacy-statement.js
  assets/js/container/imprint/imprint.js
  assets/js/container/register-maker/register-maker.js
  assets/scss/partials/_container.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/dev/debug.yaml
  config/packages/dev/nelmio_api_doc.yaml
  config/packages/dev/web_profiler.yaml
  config/packages/test/web_profiler.yaml
  config/routes/dev/web_profiler.yaml
  config/services.yaml
  package.json
  src/Domain/DomainException.php
  src/Domain/Exception/Maker/MakerAlreadyExistsException.php
  src/Domain/Exception/Maker/MakerByEmailNotFoundException.php
  src/Domain/Exception/Maker/MakerByRecoveryTokenNotFoundException.php
  src/Domain/Exception/Maker/MakerNotFoundException.php
  src/Domain/Exception/Maker/MakerWithEmailAlreadyExistsException.php
  src/Domain/Exception/NotFoundException.php
  src/Domain/Order/NotFoundException.php
  src/Domain/User/Entity/Maker.php
  src/Domain/User/NotFoundException.php
  src/Domain/User/Repository/MakerRepository.php
  src/Domain/User/RequesterNotFoundException.php
  src/Infrastructure/Controller/MakerController.php
  src/Infrastructure/Controller/MakerRegistrationController.php
  src/Infrastructure/Dto/Maker/MakerRequest.php
  src/Infrastructure/Dto/Maker/MakerResponse.php
  src/Infrastructure/Dto/MakerRegistration/MakerRegistrationRequest.php
  src/Infrastructure/Dto/MakerRegistration/MakerRegistrationResponse.php
  src/Infrastructure/Dto/ValidationError/ErrorResponse.php
  src/Infrastructure/Dto/ValidationError/ValidationErrorResponse.php
  src/Infrastructure/EventListener/ValidationErrorExceptionListener.php
  src/Infrastructure/Exception/ValidationErrorException.php
  src/Infrastructure/Validator/MakerUniqueEmail.php
  src/Infrastructure/Validator/MakerUniqueEmailValidator.php
  symfony.lock
  yarn.lock
Labels: backend, frontend

#236 Feature/frontend tests
  Makefile
  assets/js/component/modal/login.js
  cypress/integration/anonymous_spec.js
  cypress/integration/maker_registration_spec.js
  cypress/integration/maker_spec.js
  cypress/integration/requester_spec.js
  cypress/integration/things_search_spec.js
  cypress/integration/user_spec.js
  cypress/support/commands.js
Labels: frontend

#243 feature/dashbord-maker
  assets/js/app.js
  assets/js/component/user/user-nav.js
  assets/js/constants/UserRoles.js
  assets/js/container/dashboard/dashboard.js
  src/Domain/User/MakerNotFoundException.php
  src/Infrastructure/Controller/OrderController.php
Labels: backend, frontend
